-- AlterTable
ALTER TABLE "Comment" ADD COLUMN     "angryCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "careCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hahaCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "likeCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "sadCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "wowCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "angryCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "careCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hahaCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "likeCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "sadCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "wowCount" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "saved" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "share" SET DEFAULT ARRAY[]::TEXT[];
